name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Configure build for x64
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64

      # Run build
      - name: Run build (x64)
        shell: pwsh
        run: .\Build.ps1 RELEASE x64 $True
        
      - name: Configure build for x86
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64_x86
          
      # Run build
      - name: Run build (x86)
        shell: pwsh
        run: .\Build.ps1 RELEASE x86 $True
        
      - name: Configure build for arm
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64_arm
          
      # Run build
      - name: Run build (x86)
        shell: pwsh
        run: .\Build.ps1 RELEASE arm $True

      - name: Upload x64 artifact
        uses: actions/upload-artifact@v3
        with:
          path: bin/stadia-vigem-x64.exe

      - name: Upload x86 artifact
        uses: actions/upload-artifact@v3
        with:
          path: bin/stadia-vigem-x86.exe

      - name: Upload arm artifact
        uses: actions/upload-artifact@v3
        with:
          path: bin/stadia-vigem-arm.exe
