name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    name: ${{ matrix.friendlyName }} ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        arch: [x64, arm64]
        include:
          - os: macos-10.15
            friendlyName: macOS
          - os: windows-2019
            friendlyName: Windows

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Configure build for arm
        if: matrix.arch == "arm64"
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64_arm64

      # Run build
      - name: Run build (arm64)
        if: matrix.arch == "arm64"
        shell: pwsh
        run: .\Build.ps1 RELEASE arm64 $True

      - name: Upload arm64 artifact
        if: matrix.arch == "arm64"
        uses: actions/upload-artifact@v3
        with:
          path: bin/stadia-vigem-arm64.exe

      - name: Configure build for x64
        if: matrix.arch == "x64"
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64

      # Run build
      - name: Run build (x64)
        if: matrix.arch == "x64"
        shell: pwsh
        run: .\Build.ps1 RELEASE x64 $True
        
      - name: Upload x64 artifact
        if: matrix.arch == "x64"
        uses: actions/upload-artifact@v3
        with:
          path: bin/stadia-vigem-x64.exe

      - name: Configure build for x86
        if: matrix.arch == "x64"
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64_x86
          
      # Run build
      - name: Run build (x86)
        shell: pwsh
        if: matrix.arch == "x64"
        run: .\Build.ps1 RELEASE x86 $True

      - name: Upload x86 artifact
        if: matrix.arch == "x64"
        uses: actions/upload-artifact@v3
        with:
          path: bin/stadia-vigem-x86.exe
